[package]
name = "kira"
version = "0.6.0-beta.5"
authors = ["Andrew Minnich <aminnich3@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Expressive audio library for games"
repository = "https://github.com/tesselode/kira"
keywords = ["gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "../../README.md"

[dependencies]
atomic-arena = "0.1.0"
ringbuf = "0.2.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.cpal]
version = "0.13.5"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies.cpal]
version = "0.13.5"
optional = true
features = ["wasm-bindgen"]

[features]
default = ["cpal"]
