[package]
name = "kira-symphonia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kira = { path = "../kira" }
ringbuf = "0.2.6"
symphonia = "0.4.0"
