[package]
name = "kira-flac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
claxon = "0.4.3"
kira = { path = "../kira" }
kira-streaming = { path = "../kira-streaming" }
