name: Check Book

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: install cpal dependencies
        run: sudo apt-get install libasound2-dev
      - name: install mdbook
        run: cargo install mdbook
      - name: build kira
        run: cargo build -p kira
      - name: run book tests
        run: mdbook test docs -L target/debug/deps
